### ISSUE TITLE
Rusty Engine 3.0

### ISSUE THREAD

**Issue by CleanCut** [CleanCut/rusty_engine#16]
## Big Important Stuff for 3.0

- [x] Volume for sound effects, done in https://github.com/CleanCut/rusty_engine/pull/14
- [x] Make it so users can access a user-defined custom state struct instead of using generic vectors and hash maps on the GameState struct. Work in progress in https://github.com/CleanCut/rusty_engine/pull/15
- [x] Enable users to bring their own assets
  - [x] sfx & music - done in #20 
  - [x] sprites - done in #24 
  - [x] fonts - done in https://github.com/CleanCut/rusty_engine/pull/19

## Other stuff that I managed to get done for 3.0
- [x] As part of this, I'd like the constants to show up on the index page of the documentation - done in https://github.com/CleanCut/rusty_engine/pull/23
- [x] Write a proper tutorial, resolves #10, done in #25 and #26
- [x] I don't really like the `Actor` and `TextActor` abstractions. The point of this engine is to _avoid_ abstractions. Let's rename them `Sprite` and `Text`, respectively. Done in #21 and #22

## Decided to do later

- https://github.com/CleanCut/rusty_engine/pull/17
- Complete more scenarios references and/or instructions
  - Began one in https://github.com/CleanCut/rusty_engine/pull/12
- Make sure everything is documented (this is _mostly_ done, but I need to do a final pass)
- A supported way to load/save state

**Comment by CleanCut** [comment]
<img width="1348" alt="example-screenshot" src="https://user-images.githubusercontent.com/5838512/146858022-1d91c7f4-8b21-4f85-a72a-c4b93edcabc6.png">

Screenshot of the updated example.

**Comment by CleanCut** [comment]
[You can provide your own user-defined struct for game state, now!](https://github.com/CleanCut/rusty_engine/pull/15)

**Comment by CleanCut** [comment]
[Now you can choose a font for your text actor!](https://github.com/CleanCut/rusty_engine/pull/19)

**Comment by CleanCut** [comment]
[You can now play custom sound effects and music!](https://github.com/CleanCut/rusty_engine/pull/20)

**Comment by CleanCut** [comment]
Removed unnecessary "Actor" terminology:
- `Actor` is now `Sprite`
- `TextActor` is now `Text`

**Comment by CleanCut** [comment]
[You can now load arbitrary images as sprites!](https://github.com/CleanCut/rusty_engine/pull/24) Also, there is a `collider_creator` example that will let you load a sprite and create a collider file for it, as in the screenshot below (this random image file is _not_ in the asset pack).
<img width="1392" alt="Screen Shot 2021-12-26 at 10 45 40 PM" src="https://user-images.githubusercontent.com/5838512/147438683-c8af2db7-66dd-463c-a269-d03f37869496.png">

Oh, and colliders can now (optionally) be rendered with debug lines. Very nice. 😄

**Comment by CleanCut** [comment]
There is now a [Rusty Engine Tutorial](https://cleancut.github.io/rusty_engine/)!

**Comment by CleanCut** [comment]
✅ Rusty Engine 3.0 is released! 🥳 🎉
